"""Calibrate solar twin parameters on the real Indian plants (R1).

Fitted on daylight hours without inverter outages:
    ac = min(k * irr/1000 * (1 + gamma * (t_mod - 25)), ac_cap)
Exported (config/calibration/solar.yaml): gamma_pdc, realism AR(1) phi/sigma of the relative residual,
outage statistics. Nameplate capacity of the Kaggle plants is unknown, so system_loss_frac is NOT transferred.
"""
from __future__ import annotations

import numpy as np
import pandas as pd
import yaml
from scipy.optimize import least_squares

from terra.logs import get_logger
from terra.paths import CONFIG_DIR, DOCS
from terra.real.loaders import load_kaggle_solar

log = get_logger(__name__)


def fit_plant(df: pd.DataFrame) -> dict:
    d = df.dropna(subset=["ac_mw", "irradiation_wm2", "t_mod"])
    d = d[(d["irradiation_wm2"] > 150) & (d["inverter_outage_frac"].fillna(0) < 0.01)]
    ac_cap = float(d["ac_mw"].quantile(0.995))
    irr, tm, y = d["irradiation_wm2"].to_numpy() / 1000, d["t_mod"].to_numpy(), d["ac_mw"].to_numpy()

    def model(p: np.ndarray) -> np.ndarray:
        k, gamma = p
        return np.minimum(k * irr * (1 + gamma * (tm - 25)), ac_cap)

    res = least_squares(lambda p: model(p) - y, x0=[ac_cap * 1.1, -0.004], bounds=([0, -0.01], [ac_cap * 3, 0]))
    k, gamma = res.x
    rel = (y - model(res.x)) / np.maximum(model(res.x), 1e-3)
    rel = pd.Series(rel, index=d.index)
    phi = float(rel.autocorr(lag=1)) if len(rel) > 10 else 0.5
    sigma = float(np.std(rel) * np.sqrt(max(1 - phi**2, 1e-3)))
    # outages: hours with any inverter down during daylight
    day = df[df["irradiation_wm2"] > 150]
    down = (day["inverter_outage_frac"].fillna(0) > 0).astype(int)
    starts = int(((down.diff() == 1) | ((down == 1) & (down.shift().isna()))).sum())
    days = max(len(day) / 12, 1)
    mean_dur = float(down.sum() / max(starts, 1))
    return {"k_mw_per_kwm2": float(k), "gamma_pdc": float(gamma), "ac_cap_mw": ac_cap,
            "fit_nmae_pct": float(100 * np.mean(np.abs(model(res.x) - y)) / ac_cap),
            "ar1_phi": float(np.clip(phi, 0, 0.95)), "ar1_sigma": float(np.clip(sigma, 0.01, 0.2)),
            "outage_rate_per_day": float(starts / days), "outage_mean_hours": mean_dur,
            "outage_capacity_frac": float(day["inverter_outage_frac"][day["inverter_outage_frac"] > 0].mean())
            if (day["inverter_outage_frac"] > 0).any() else 0.05}


def run() -> dict:
    results = {f"plant_{p}": fit_plant(load_kaggle_solar(p)) for p in (1, 2)}
    avg = {k: float(np.mean([r[k] for r in results.values()])) for k in
           ("gamma_pdc", "ar1_phi", "ar1_sigma", "outage_rate_per_day", "outage_mean_hours", "outage_capacity_frac")}
    out = {"source": "Kaggle Solar Power Generation Data (2 Indian plants, 34 days)", "per_plant": results,
           "recommended": avg}
    (CONFIG_DIR / "calibration").mkdir(parents=True, exist_ok=True)
    (CONFIG_DIR / "calibration" / "solar.yaml").write_text(yaml.safe_dump(out, sort_keys=False))
    lines = ["## Solar calibration (R1)", "", pd.DataFrame(results).T.round(4).to_markdown(), "",
             "Recommended values (copy into config/site.yaml after review):", "", "```yaml",
             yaml.safe_dump(avg, sort_keys=False), "```", ""]
    _append_doc(lines)
    log.info("solar calibration: %s", avg)
    return out


def _append_doc(lines: list[str]) -> None:
    DOCS.mkdir(parents=True, exist_ok=True)
    p = DOCS / "calibration.md"
    head = "" if p.exists() else "# Calibration of the digital twin\n\nGenerated by `terra calibrate`.\n\n"
    with open(p, "a", encoding="utf-8") as f:
        f.write(head + "\n".join(lines) + "\n")
