/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness/readiness probe. Accepts HEAD too: uptime pingers (UptimeRobot) often probe with HEAD.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Health
         * @description Liveness/readiness probe. Accepts HEAD too: uptime pingers (UptimeRobot) often probe with HEAD.
         */
        head: operations["health_health_get"];
        patch?: never;
        trace?: never;
    };
    "/health/deep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Deep
         * @description Keep-warm probe: like /health but also makes one tiny query against the database (wakes a suspended
         *     Neon compute). Always HTTP 200 so a pinger does not page on a slow wake-up; read the `db` field.
         */
        get: operations["health_deep_health_deep_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Health Deep
         * @description Keep-warm probe: like /health but also makes one tiny query against the database (wakes a suspended
         *     Neon compute). Always HTTP 200 so a pinger does not page on a slow wake-up; read the `db` field.
         */
        head: operations["health_deep_health_deep_get"];
        patch?: never;
        trace?: never;
    };
    "/site": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Site */
        get: operations["site_site_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast */
        get: operations["forecast_forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History
         * @description Actual vs predicted on the held-out test period (day-ahead issues at 00 UTC).
         */
        get: operations["history_forecast_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare */
        get: operations["compare_models_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alerts */
        get: operations["alerts_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert_id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ack */
        post: operations["ack_alerts__alert_id__ack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream
         * @description Server-Sent Events: 'run_complete' and 'alert' events pushed by the scheduler.
         */
        get: operations["stream_alerts_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dispatch */
        get: operations["dispatch_dispatch_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whatif": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Whatif */
        post: operations["whatif_whatif_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dsm/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_dsm_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dsm/schedule.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Schedule */
        get: operations["schedule_dsm_schedule_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Impact */
        get: operations["impact_impact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assumptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assumptions */
        get: operations["assumptions_assumptions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trust Summary */
        get: operations["trust_summary_trust_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Locations
         * @description The allowlist the /location page offers.
         */
        get: operations["locations_locations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{location_id}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start
         * @description Start (or reuse, if under 30 minutes old) a live forecast for one allowlisted site, with the caller's plant profile.
         */
        post: operations["start_locations__location_id__forecast_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_locations_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/jobs/{job_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Result */
        get: operations["result_locations_jobs__job_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Profile Schema
         * @description Fields, steps and defaults that drive the onboarding wizard and the Settings page.
         */
        get: operations["profile_schema_profile_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Profile Check
         * @description Validate a plant profile and show what it resolves to. Nothing is stored on the server.
         */
        post: operations["profile_check_profile_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertOut */
        AlertOut: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Source */
            source: string;
            /** Start Utc */
            start_utc: string;
            /** End Utc */
            end_utc: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "critical";
            /** Probability */
            probability: number;
            /** Magnitude Mw */
            magnitude_mw: number;
            /** Message */
            message: string;
            /** Issue Time Utc */
            issue_time_utc: string;
            /**
             * Acknowledged
             * @default false
             */
            acknowledged: boolean;
        };
        /** DispatchPoint */
        DispatchPoint: {
            /** Target Time Utc */
            target_time_utc: string;
            /** Gen Mw */
            gen_mw: number;
            /** Demand Mw */
            demand_mw: number;
            /** Charge Mw */
            charge_mw: number;
            /** Discharge Mw */
            discharge_mw: number;
            /** Soc Mwh */
            soc_mwh: number;
            /** Backup Mw */
            backup_mw: number;
            /** Curtail Mw */
            curtail_mw: number;
        };
        /** DispatchResponse */
        DispatchResponse: {
            /**
             * Strategy
             * @enum {string}
             */
            strategy: "advisor" | "rule" | "none";
            /** Points */
            points: components["schemas"]["DispatchPoint"][];
            /** Kpis */
            kpis: {
                [key: string]: components["schemas"]["Kpis"];
            };
        };
        /** DsmRow */
        DsmRow: {
            /** Source */
            source: string;
            /** Strategy */
            strategy: string;
            /** Charge Inr */
            charge_inr: number;
            /** Blocks Outside Tolerance Pct */
            blocks_outside_tolerance_pct: number;
        };
        /** DsmSummary */
        DsmSummary: {
            /** Illustrative Rates */
            illustrative_rates: boolean;
            /** Chosen Level */
            chosen_level: {
                [key: string]: number;
            };
            /** Rows */
            rows: components["schemas"]["DsmRow"][];
        };
        /** ForecastPoint */
        ForecastPoint: {
            /** Target Time Utc */
            target_time_utc: string;
            /** Lead H */
            lead_h: number;
            /** Q05 */
            q05: number;
            /** Q10 */
            q10: number;
            /** Q50 */
            q50: number;
            /** Q90 */
            q90: number;
            /** Q95 */
            q95: number;
            /** Trust Score */
            trust_score: number;
            /** Trust Level */
            trust_level: string;
            /** Trust Reason */
            trust_reason: string;
        };
        /** ForecastResponse */
        ForecastResponse: {
            /**
             * Source
             * @enum {string}
             */
            source: "solar" | "wind" | "hybrid";
            /** Issue Time Utc */
            issue_time_utc: string;
            /** Mode */
            mode: string;
            /** Capacity Mw */
            capacity_mw: number;
            /** Points */
            points: components["schemas"]["ForecastPoint"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Mode */
            mode: string;
            /** Latest Run */
            latest_run?: string | null;
            /** Latest Issue Time Utc */
            latest_issue_time_utc?: string | null;
        };
        /** HistoryPoint */
        HistoryPoint: {
            /** Target Time Utc */
            target_time_utc: string;
            /** Actual Mw */
            actual_mw: number;
            /** Q10 */
            q10: number;
            /** Q50 */
            q50: number;
            /** Q90 */
            q90: number;
        };
        /** HistoryResponse */
        HistoryResponse: {
            /**
             * Source
             * @enum {string}
             */
            source: "solar" | "wind";
            /** Model */
            model: string;
            /** Lead H Max */
            lead_h_max: number;
            /** Points */
            points: components["schemas"]["HistoryPoint"][];
        };
        /** ImpactResponse */
        ImpactResponse: {
            /** Impact */
            impact: {
                [key: string]: unknown;
            };
            /** Value Of Forecast */
            value_of_forecast: {
                [key: string]: unknown;
            }[];
            /** Hybrid */
            hybrid: {
                [key: string]: unknown;
            };
            /** Sources */
            sources: string[];
        };
        /** Kpis */
        Kpis: {
            /** Backup Mwh */
            backup_mwh: number;
            /** Curtail Mwh */
            curtail_mwh: number;
            /** Cost Inr */
            cost_inr: number;
            /** Co2 T */
            co2_t: number;
            /** Battery Throughput Mwh */
            battery_throughput_mwh: number;
        };
        /** LocationInfo */
        LocationInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Region */
            region: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Altitude M */
            altitude_m: number;
            /** Note */
            note: string;
            /** Is Home */
            is_home: boolean;
        };
        /** LocationJob */
        LocationJob: {
            /** Job Id */
            job_id: string;
            /** Location Id */
            location_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "failed";
            /**
             * Step
             * @enum {string}
             */
            step: "queued" | "weather" | "models" | "plan" | "done";
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Error */
            error?: string | null;
            /**
             * Reused
             * @default false
             */
            reused: boolean;
        };
        /** LocationResult */
        LocationResult: {
            location: components["schemas"]["LocationInfo"];
            /** Issue Time Utc */
            issue_time_utc: string;
            /** Generated At */
            generated_at: string;
            /** Solar */
            solar: components["schemas"]["ForecastPoint"][];
            /** Wind */
            wind: components["schemas"]["ForecastPoint"][];
            /** Hybrid */
            hybrid: components["schemas"]["ForecastPoint"][];
            /** Dispatch */
            dispatch: components["schemas"]["DispatchPoint"][];
            kpis: components["schemas"]["Kpis"];
            /** Dispatch By Strategy */
            dispatch_by_strategy: {
                [key: string]: components["schemas"]["DispatchPoint"][];
            };
            /** Kpis By Strategy */
            kpis_by_strategy: {
                [key: string]: components["schemas"]["Kpis"];
            };
            /** Alerts */
            alerts: components["schemas"]["AlertOut"][];
            /** Validated Here */
            validated_here: boolean;
            /** Caveat */
            caveat: string;
            /** Attribution */
            attribution: string;
            plant: components["schemas"]["PlantSummary"];
        };
        /** ModelRow */
        ModelRow: {
            /** Model */
            model: string;
            /** Mae */
            mae: number;
            /** Rmse */
            rmse: number;
            /** Nmae Pct */
            nmae_pct: number;
            /** Nrmse Pct */
            nrmse_pct: number;
            /** Bias */
            bias: number;
            /** Picp80 */
            picp80: number;
            /** Picp90 */
            picp90: number;
            /** Mpiw80 Pct */
            mpiw80_pct: number;
            /** Skill Vs Persistence */
            skill_vs_persistence?: number | null;
            /** Lead Bucket */
            lead_bucket?: string | null;
        };
        /** ModelsResponse */
        ModelsResponse: {
            /**
             * Source
             * @enum {string}
             */
            source: "solar" | "wind";
            /** Split */
            split: string;
            /** Rows */
            rows: components["schemas"]["ModelRow"][];
            /**
             * Daylight Only
             * @default false
             */
            daylight_only: boolean;
        };
        /** PlantSummary */
        PlantSummary: {
            /** Plant Name */
            plant_name: string;
            /** Location */
            location: string;
            /** Solar Ac Mw */
            solar_ac_mw: number;
            /** Wind Mw */
            wind_mw: number;
            /** Battery Mw */
            battery_mw: number;
            /** Battery Mwh */
            battery_mwh: number;
            /** Demand Peak Mw */
            demand_peak_mw: number;
            /** Solar Scale */
            solar_scale: number;
            /** Wind Scale */
            wind_scale: number;
            /** Entered */
            entered: string[];
            /** Customised */
            customised: boolean;
        };
        /** ProfileBody */
        ProfileBody: {
            /**
             * Values
             * @default {}
             */
            values: {
                [key: string]: string | number | null;
            };
        };
        /** ProfileCheck */
        ProfileCheck: {
            /** Clean */
            clean: {
                [key: string]: string | number;
            };
            /** Errors */
            errors: {
                [key: string]: string;
            };
            summary?: components["schemas"]["PlantSummary"] | null;
        };
        /** SiteInfo */
        SiteInfo: {
            /** Name */
            name: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Timezone */
            timezone: string;
            /** Solar Ac Mw */
            solar_ac_mw: number;
            /** Wind Mw */
            wind_mw: number;
            /** Battery Mw */
            battery_mw: number;
            /** Battery Mwh */
            battery_mwh: number;
            /** Attribution */
            attribution: string;
            /** Plant Note */
            plant_note: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WhatIfRequest */
        WhatIfRequest: {
            /**
             * Irradiance Scale
             * @default 1
             */
            irradiance_scale: number;
            /**
             * Wind Scale
             * @default 1
             */
            wind_scale: number;
            /** Solar Ac Mw */
            solar_ac_mw?: number | null;
            /** Wind Turbines */
            wind_turbines?: number | null;
            /** Battery Mw */
            battery_mw?: number | null;
            /** Battery Mwh */
            battery_mwh?: number | null;
        };
        /** WhatIfResponse */
        WhatIfResponse: {
            before: components["schemas"]["WhatIfSide"];
            after: components["schemas"]["WhatIfSide"];
        };
        /** WhatIfSide */
        WhatIfSide: {
            /** Energy Mwh P50 */
            energy_mwh_p50: number;
            kpis: components["schemas"]["Kpis"];
            /** Points */
            points: {
                [key: string]: unknown;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    health_deep_health_deep_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_deep_health_deep_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    site_site_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteInfo"];
                };
            };
        };
    };
    forecast_forecast_get: {
        parameters: {
            query?: {
                source?: "solar" | "wind" | "hybrid";
                horizon?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_forecast_history_get: {
        parameters: {
            query?: {
                source?: "solar" | "wind";
                model?: string;
                start?: string | null;
                end?: string | null;
                lead_h_max?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_models_compare_get: {
        parameters: {
            query?: {
                source?: "solar" | "wind";
                split?: "val_cal" | "test";
                by?: "lead_bucket" | null;
                daylight?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alerts_alerts_get: {
        parameters: {
            query?: {
                active_after?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ack_alerts__alert_id__ack_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_alerts_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    dispatch_dispatch_get: {
        parameters: {
            query?: {
                strategy?: "advisor" | "rule" | "none";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DispatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whatif_whatif_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhatIfRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatIfResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_dsm_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DsmSummary"];
                };
            };
        };
    };
    schedule_dsm_schedule_csv_get: {
        parameters: {
            query?: {
                source?: "solar" | "wind" | "hybrid";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    impact_impact_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpactResponse"];
                };
            };
        };
    };
    assumptions_assumptions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    trust_summary_trust_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    locations_locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationInfo"][];
                };
            };
        };
    };
    start_locations__location_id__forecast_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path: {
                location_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProfileBody"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_locations_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    result_locations_jobs__job_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_schema_profile_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    profile_check_profile_check_post: {
        parameters: {
            query?: {
                location_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileCheck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
