/** Friendly aliases over the generated OpenAPI types (schema.d.ts is generated by `make types`). */
import type { components } from "./schema";

type S = components["schemas"];
export type Health = S["Health"];
export type SiteInfo = S["SiteInfo"];
export type ForecastResponse = S["ForecastResponse"];
export type ForecastPoint = S["ForecastPoint"];
export type HistoryResponse = S["HistoryResponse"];
export type ModelsResponse = S["ModelsResponse"];
export type ModelRow = S["ModelRow"];
export type AlertOut = S["AlertOut"];
export type DispatchResponse = S["DispatchResponse"];
export type Kpis = S["Kpis"];
export type WhatIfRequest = S["WhatIfRequest"];
export type WhatIfResponse = S["WhatIfResponse"];
export type DsmSummary = S["DsmSummary"];
export type ImpactResponse = S["ImpactResponse"];
export type Source = "solar" | "wind" | "hybrid";
