"""Generate baseline-results.md for T3.5.1."""
import pandas as pd
from terra.config import load_config
from terra.eval.backtest import long_predictions
from terra.eval.metrics import metrics_table
from terra.features.build_features import xy
from terra.models.baselines import Persistence, WeekMean
from terra.models.physics import Physics
from terra.paths import DATA_PROCESSED, DOCS

cfg = load_config()
lines = ["# Baseline results (validation split)", "",
         "Generated by `terra backtest` on validation data — **NO** test data seen.", ""]
for s in ("solar", "wind"):
    f = pd.read_parquet(DATA_PROCESSED / f"framed_{s}.parquet")
    Xtr, ytr = xy(f, "train")
    Xva, yva = xy(f, "val")
    cap = cfg.capacity_mw(s)
    preds = {m.name: m.fit(Xtr, ytr).predict(Xva)
             for m in (Persistence(cap, s), WeekMean(cap, s), Physics(cap, s))}
    lp = long_predictions(f[f["split"] == "val"], preds, s)
    t = metrics_table(lp, cap)
    lines += [
        f"## {s.title()}",
        "",
        t[["model", "mae", "rmse", "nmae_pct", "picp80", "skill_vs_persistence"]].round(3).to_markdown(index=False),
        "",
        f"> Physics skill vs persistence: {t.loc[t['model']=='physics','skill_vs_persistence'].iloc[0]:.3f}",
        "",
    ]

(DOCS / "baseline-results.md").write_text("\n".join(lines))
print("baseline-results.md written")
